### ISSUE TITLE
Homepage URL is broken

### ISSUE THREAD

**Issue by technicalpickles** [markokaestner/of-task-actions#22]
It is currently 404ing:
- http://markokaestner.com/projects/of-task-actions-master-omnifocus-tasks-with-alfred 

Navigating through projects, it looks like the correct URL is: 
- http://markokaestner.com/projects/of-task-actions-master-your-omnifocus-tasks-from-alfred

**Comment by markokaestner** [comment]
Thanks for pointing that out. Missed that one when I migrated the blog.
